# Generated by Django 5.2.5 on 2025-09-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodel",
            options={},
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="products.categorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
