# Generated by Django 5.2.6 on 2025-09-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_tagmodel_producttagmodel_productmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturermodel',
            old_name='title',
            new_name='name',
        ),
    ]
