# Generated by Django 5.2.6 on 2025-09-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_title_manufacturermodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manufacturermodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producttagmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
