# Generated by Django 5.2.6 on 2025-10-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colormodel_title_en_colormodel_title_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_of_the_day', to='products.productmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
