# Generated by Django 5.2.6 on 2025-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_dealofthedaymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealofthedaymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
    ]
