# Generated by Django 5.2.6 on 2025-10-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_dealofthedaymodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategorymodel',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
