# Generated by Django 5.2.6 on 2025-10-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productcategorymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='dealofthedaymodel',
            options={'verbose_name': 'deal', 'verbose_name_plural': 'deals'},
        ),
        migrations.AlterModelOptions(
            name='manufacturermodel',
            options={'verbose_name': 'manufacturer', 'verbose_name_plural': 'manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='producttagmodel',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
