# Generated by Django 5.2.6 on 2025-10-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_colormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealofthedaymodel',
            options={},
        ),
    ]
