# Generated by Django 5.2.5 on 2025-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="city",
            field=models.CharField(default="Tashkent", max_length=100),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="district",
            field=models.CharField(default="Unknown district", max_length=100),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="home_number",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("uzum", "Uzum Bank"),
                    ("agrobank", "Agrobank"),
                    ("tbc", "TBC Bank"),
                    ("cash", "Cash Payment"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="street",
            field=models.CharField(default="Unknown street", max_length=255),
        ),
    ]
