# Generated by Django 5.2.5 on 2025-10-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_ordermodel_additional_info_ordermodel_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="unique_id",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
