# Generated by Django 5.2.6 on 2025-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthormodel',
            name='updatet_at',
        ),
        migrations.RemoveField(
            model_name='blogcategorymodel',
            name='updatet_at',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='updatet_at',
        ),
        migrations.RemoveField(
            model_name='blogtagmodel',
            name='updatet_at',
        ),
        migrations.RemoveField(
            model_name='blogviewmodel',
            name='updatet_at',
        ),
        migrations.AddField(
            model_name='blogauthormodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogcategorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogtagmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogauthormodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogcategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogtagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogviewmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
