# Generated by Django 5.2.6 on 2025-09-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogauthormodel_updatet_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blogs.blogcategorymodel'),
        ),
    ]
