# Generated by Django 5.2.5 on 2025-10-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_blogauthormodel_bio_en_blogauthormodel_bio_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogauthormodel",
            name="full_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="blogauthormodel",
            name="full_name_en",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="blogauthormodel",
            name="full_name_ru",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="blogauthormodel",
            name="full_name_uz",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
