# Generated by Django 5.2.5 on 2025-10-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_blogcommentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcommentmodel",
            name="blog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blogs.blogmodel",
            ),
        ),
    ]
