# Generated by Django 5.2.5 on 2025-08-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPagesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subject", models.CharField(blank=True, max_length=128, null=True)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.DeleteModel(
            name="ContactModel",
        ),
    ]
