# Generated by Django 5.2.6 on 2025-09-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactmodel_created_at_contactmodel_updatet_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='updatet_at',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
