# Generated by Django 5.2.6 on 2025-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_contactmodel_updatet_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
