# Generated by Django 5.2.6 on 2025-09-24 19:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmodel_message_en_contactmodel_message_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('text', models.CharField(max_length=128)),
                ('text_en', models.CharField(max_length=128, null=True)),
                ('text_uz', models.CharField(max_length=128, null=True)),
                ('text_ru', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
            },
        ),
    ]
