# Generated by Django 5.2.6 on 2025-10-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_bannermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='text_uz',
        ),
        migrations.RemoveField(
            model_name='bannermodel',
            name='url',
        ),
    ]
