# Generated by Django 5.2.6 on 2025-10-02 17:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_bannermodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='title_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='title_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
