# Generated by Django 5.2.6 on 2025-10-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='added_at',
        ),
    ]
